#Tells Travis we need super user level permissions
sudo: required
#Travis installs docker
services:
  - docker

#Execute before tests and everything else
before_install:
  - gem install bundler
  - docker build -t frontend-travis-ci -f Dockerfile.dev .

script:
  - docker run frontend-travis-ci npm run test -- --coverage