version: '3'
services:
  web:
    build: 
      # where are all the files we need for build
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /home/docker/projects:/app